name: Upload SBOM to OWASP Dependency Track
on:
  push:
    branches: [main]
jobs:
  upload-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: generate SBOM
        run: npm install && npm run generate:bom
      - name: upload to OWASP Dependency Track
        uses: DependencyTrack/gh-upload-sbom@v3
        with:
          serverhostname: 'owasp-api.heartsciences.com'
          apikey: odt_1B1EK2W3XQ8hk3XeYJdeQqmQhV6yL2PB
          projectname: Test123
          projectversion: test
          bomfilename: bom.json
          autocreate: true
